name: Deploy Remix SSR App to Azure App Service
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
 
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
 
      - name: Install dependencies
        run: npm install
 
      - name: Build Remix App
        run: npm run build
 
      - name: Copy static files to public (optional)
        run: |
          mkdir -p public/build
          cp -r build/client/* public/build/
 
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: YOUR_AZURE_APP_NAME
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .